[package]
name = "aide-docs"
edition.workspace = true
version.workspace = true

[dependencies]
syn = { version = "2.0.100", features = ["full"] }
quote = "1.0.40"
proc-macro2 = "1.0.94"

[lib]
proc-macro = true
